<div>
    <?php if (!empty($messages['success'])) : ?>
        <?php foreach ($messages['success'] as $message) : ?>
            <p style="color: green;"><?= $message ?></p>
        <?php endforeach; ?>
    <?php endif ?>

    <form action="/users" method="GET">
        <input type="text" name="term" value="<?= htmlspecialchars($term) ?>">
    </form>
    <?php foreach ($users as $user) : ?>
        <p>
            <a href="/users/<?= $user['id'] ?>">
                <?= htmlspecialchars($user['nickname']) ?>
            </a>
        </p>
    <?php endforeach ?>
</div>
